language: python

python:
  - "2.7"

before_script:
  - echo "yes" | sudo add-apt-repository ppa:apokluda/boost1.53
  - sudo apt-get update
  - sudo apt-get install --assume-yes libhdf5-serial-dev libboost-thread1.53-dev libboost-python1.53-dev libjpeg-dev libtiff4-dev libpng12-dev libfftw3-dev cmake
  - pip install nose
  - pip install numpy
   
script:
  - mkdir build && cd build
  - cmake -DCMAKE_BUILD_TYPE=Release -DDEPENDENCY_SEARCH_PREFIX=$VIRTUAL_ENV -DAUTOBUILD_TESTS=1 -DAUTOEXEC_TESTS=0 -DVIGRANUMPY_LIBRARIES="/usr/lib/libpython2.7.so;/usr/lib/libboost_python.so" ..
  - make
  - make test
